/// Go board representation — mirrors `cpp/game/board.h` and `cpp/game/board.cpp`.
///
/// # Loc encoding
/// `(x, y)` → `(x+1) + (y+1) * (x_size+1)`.  Special values:
/// * `NULL_LOC = 0`  — "no location"
/// * `PASS_LOC = 1`  — pass move
///
/// # Layout
/// The board array is sized `MAX_ARR_SIZE = (MAX_LEN+1)*(MAX_LEN+2)+1 = 421`
/// for 19×19.  Row `y` starts at offset `(y+1)*(x_size+1)`.  A one-cell
/// wall border surrounds the playable area.
///
/// # Chain tracking
/// Each stone group (chain) is a **circular linked list** stored in
/// `next_in_chain`.  `chain_head[loc]` points to the canonical head of the
/// chain; `chain_data[head]` holds `{owner, num_locs, num_liberties}`.
use std::sync::OnceLock;

use crate::game::Hash128;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

pub const MAX_LEN: usize = 19;
/// `(MAX_LEN+1)*(MAX_LEN+2)+1` = 421 for MAX_LEN=19.
pub const MAX_ARR_SIZE: usize = (MAX_LEN + 1) * (MAX_LEN + 2) + 1;

pub const NULL_LOC: Loc = 0;
pub const PASS_LOC: Loc = 1;

/// Compact board index.  Encoded as `(x+1) + (y+1)*(x_size+1)`.
pub type Loc = i16;

// ---------------------------------------------------------------------------
// Colour / Player
// ---------------------------------------------------------------------------

#[derive(Copy, Clone, Debug, Eq, PartialEq, Default)]
#[repr(u8)]
pub enum Color {
  #[default]
  Empty = 0,
  Black = 1,
  White = 2,
  Wall = 3,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum Player {
  Black = 1,
  White = 2,
}

impl Player {
  pub fn opponent(self) -> Self {
    match self {
      Player::Black => Player::White,
      Player::White => Player::Black,
    }
  }

  pub fn color(self) -> Color {
    match self {
      Player::Black => Color::Black,
      Player::White => Color::White,
    }
  }
}

impl Color {
  pub fn is_stone(self) -> bool {
    matches!(self, Color::Black | Color::White)
  }

  pub fn player(self) -> Option<Player> {
    match self {
      Color::Black => Some(Player::Black),
      Color::White => Some(Player::White),
      _ => None,
    }
  }
}

// ---------------------------------------------------------------------------
// Move
// ---------------------------------------------------------------------------

#[derive(Copy, Clone, Debug)]
pub struct Move {
  pub loc: Loc,
  pub player: Player,
}

// ---------------------------------------------------------------------------
// Chain data
// ---------------------------------------------------------------------------

#[derive(Copy, Clone, Debug, Default)]
pub struct ChainData {
  pub owner: u8, // 1=Black 2=White, 0=unused
  pub num_locs: u16,
  pub num_liberties: u16,
}

// ---------------------------------------------------------------------------
// MoveRecord — for undo
// ---------------------------------------------------------------------------

/// Enough information to undo a single move.
#[derive(Clone, Debug)]
pub struct MoveRecord {
  pub loc: Loc,
  pub player: Player,
  pub ko_loc: Loc,
  pub captures: Vec<CaptureRecord>,
  pub pos_hash_before: Hash128,
  pub num_black_captures_before: i32,
  pub num_white_captures_before: i32,
}

#[derive(Clone, Debug)]
pub struct CaptureRecord {
  /// Head of the captured chain (for reconstructing chain_data/next_in_chain).
  pub head: Loc,
  pub color: Color,
  /// All stone locations in the captured group (for restoring board state).
  pub locs: Vec<Loc>,
}

// ---------------------------------------------------------------------------
// Zobrist tables (generated by build.rs)
// ---------------------------------------------------------------------------

/// All Zobrist tables in one struct; initialised once from `zobrist_tables.rs`.
struct ZobristTables {
  board_hash: [[Hash128; 4]; MAX_ARR_SIZE],
  ko_loc_hash: [Hash128; MAX_ARR_SIZE],
  size_x_hash: [Hash128; MAX_LEN + 1],
  size_y_hash: [Hash128; MAX_LEN + 1],
}

mod generated {
  include!(concat!(env!("OUT_DIR"), "/zobrist_tables.rs"));
}

pub use generated::{
  ZOBRIST_KO_LOC_HASH, ZOBRIST_KO_MARK_HASH as KO_MARK_HASH,
  ZOBRIST_PLAYER_HASH,
};

static ZOBRIST: OnceLock<ZobristTables> = OnceLock::new();

fn zobrist() -> &'static ZobristTables {
  ZOBRIST.get_or_init(|| ZobristTables {
    board_hash: generated::ZOBRIST_BOARD_HASH,
    ko_loc_hash: generated::ZOBRIST_KO_LOC_HASH,
    size_x_hash: generated::ZOBRIST_SIZE_X_HASH,
    size_y_hash: generated::ZOBRIST_SIZE_Y_HASH,
  })
}

// ---------------------------------------------------------------------------
// Location utilities
// ---------------------------------------------------------------------------

pub mod location {
  use super::*;

  pub fn get_loc(x: usize, y: usize, x_size: usize) -> Loc {
    ((x + 1) + (y + 1) * (x_size + 1)) as Loc
  }

  pub fn get_x(loc: Loc, x_size: usize) -> usize {
    (loc as usize % (x_size + 1)).wrapping_sub(1)
  }

  pub fn get_y(loc: Loc, x_size: usize) -> usize {
    (loc as usize / (x_size + 1)).wrapping_sub(1)
  }

  pub fn is_adjacent(loc1: Loc, loc2: Loc, x_size: usize) -> bool {
    let diff = (loc1 - loc2).abs() as usize;
    diff == 1 || diff == x_size + 1
  }

  /// The four cardinal adjacent offsets for board stride `x_size`.
  pub fn adj_offsets(x_size: usize) -> [i16; 4] {
    let s = (x_size + 1) as i16;
    [-s, -1, 1, s]
  }

  /// All 8 offsets (4 cardinal + 4 diagonal).
  pub fn all_offsets(x_size: usize) -> [i16; 8] {
    let s = (x_size + 1) as i16;
    [-s, -1, 1, s, -s - 1, -s + 1, s - 1, s + 1]
  }
}

// ---------------------------------------------------------------------------
// Board
// ---------------------------------------------------------------------------

pub struct Board {
  pub x_size: usize,
  pub y_size: usize,
  pub colors: [Color; MAX_ARR_SIZE],
  pub chain_data: [ChainData; MAX_ARR_SIZE],
  pub chain_head: [Loc; MAX_ARR_SIZE],
  pub next_in_chain: [Loc; MAX_ARR_SIZE],
  pub ko_loc: Loc,
  pub pos_hash: Hash128,
  pub num_black_captures: i32,
  pub num_white_captures: i32,
  /// Cached adjacent (4-dir) offsets for this board's x_size.
  adj: [i16; 4],
}

impl Clone for Board {
  fn clone(&self) -> Self {
    Board {
      x_size: self.x_size,
      y_size: self.y_size,
      colors: self.colors,
      chain_data: self.chain_data,
      chain_head: self.chain_head,
      next_in_chain: self.next_in_chain,
      ko_loc: self.ko_loc,
      pos_hash: self.pos_hash,
      num_black_captures: self.num_black_captures,
      num_white_captures: self.num_white_captures,
      adj: self.adj,
    }
  }
}

impl Board {
  // -----------------------------------------------------------------------
  // Construction
  // -----------------------------------------------------------------------

  /// Create an empty board of size `x_size × y_size` (max 19×19).
  pub fn new(x_size: usize, y_size: usize) -> Self {
    assert!(x_size >= 1 && x_size <= MAX_LEN);
    assert!(y_size >= 1 && y_size <= MAX_LEN);

    let z = zobrist();
    let mut colors = [Color::Wall; MAX_ARR_SIZE];
    let mut pos_hash = Hash128::ZERO;

    // Mark interior cells as empty; walls remain Wall.
    for y in 0..y_size {
      for x in 0..x_size {
        let loc = location::get_loc(x, y, x_size);
        colors[loc as usize] = Color::Empty;
        pos_hash ^= z.board_hash[loc as usize][Color::Empty as usize];
      }
    }

    // Mix in board-size hashes.
    pos_hash ^= z.size_x_hash[x_size];
    pos_hash ^= z.size_y_hash[y_size];

    let adj = location::adj_offsets(x_size);

    Board {
      x_size,
      y_size,
      colors,
      chain_data: [ChainData::default(); MAX_ARR_SIZE],
      chain_head: [0i16; MAX_ARR_SIZE],
      next_in_chain: [0i16; MAX_ARR_SIZE],
      ko_loc: NULL_LOC,
      pos_hash,
      num_black_captures: 0,
      num_white_captures: 0,
      adj,
    }
  }

  // -----------------------------------------------------------------------
  // Basic queries
  // -----------------------------------------------------------------------

  pub fn on_board(&self, loc: Loc) -> bool {
    loc != NULL_LOC
      && loc != PASS_LOC
      && self.colors[loc as usize] != Color::Wall
  }

  pub fn get_chain_size(&self, loc: Loc) -> u16 {
    self.chain_data[self.chain_head[loc as usize] as usize].num_locs
  }

  pub fn get_num_liberties(&self, loc: Loc) -> u16 {
    self.chain_data[self.chain_head[loc as usize] as usize].num_liberties
  }

  /// Count immediate empty neighbours of `loc` (not chain liberties).
  pub fn get_num_immediate_liberties(&self, loc: Loc) -> u16 {
    let l = loc as usize;
    let c = &self.colors;
    let a = &self.adj;
    let mut cnt = 0u16;
    if c[(l as i16 + a[0]) as usize] == Color::Empty {
      cnt += 1;
    }
    if c[(l as i16 + a[1]) as usize] == Color::Empty {
      cnt += 1;
    }
    if c[(l as i16 + a[2]) as usize] == Color::Empty {
      cnt += 1;
    }
    if c[(l as i16 + a[3]) as usize] == Color::Empty {
      cnt += 1;
    }
    cnt
  }

  // -----------------------------------------------------------------------
  // Move legality
  // -----------------------------------------------------------------------

  pub fn is_suicide(&self, loc: Loc, pla: Player) -> bool {
    if !self.on_board(loc) || self.colors[loc as usize] != Color::Empty {
      return false;
    }
    let opp = pla.opponent();
    let opp_color = opp.color();
    let pla_color = pla.color();
    for &off in &self.adj {
      let adj = (loc as i16 + off) as usize;
      let c = self.colors[adj];
      if c == Color::Empty {
        return false; // has a liberty
      }
      if c == pla_color
        && self.chain_data[self.chain_head[adj] as usize].num_liberties > 1
      {
        return false; // friendly chain has liberties to spare
      }
      if c == opp_color
        && self.chain_data[self.chain_head[adj] as usize].num_liberties == 1
      {
        return false; // captures an opponent chain
      }
    }
    true
  }

  /// True if playing `loc` for `pla` would be a ko capture (recaptures a single
  /// stone and leaves the new stone with exactly one liberty).
  pub fn would_be_ko_capture(&self, loc: Loc, pla: Player) -> bool {
    if !self.on_board(loc) || self.colors[loc as usize] != Color::Empty {
      return false;
    }
    let opp = pla.opponent();
    let opp_color = opp.color();
    let pla_color = pla.color();
    let mut num_captures = 0;
    let mut new_liberties = 0i16;
    for &off in &self.adj {
      let adj = (loc as i16 + off) as usize;
      match self.colors[adj] {
        Color::Empty => new_liberties += 1,
        c if c == opp_color => {
          if self.chain_data[self.chain_head[adj] as usize].num_liberties == 1 {
            num_captures += 1;
            let captured_size =
              self.chain_data[self.chain_head[adj] as usize].num_locs;
            if captured_size > 1 || num_captures > 1 {
              return false; // not a single-stone capture
            }
          }
        }
        c if c == pla_color => {} // friendly chain
        _ => {}
      }
    }
    // Ko: captures exactly one stone, new stone has exactly one liberty
    num_captures == 1 && (new_liberties + 1 == 1)
  }

  pub fn is_ko_banned(&self, loc: Loc) -> bool {
    self.ko_loc == loc
  }

  pub fn is_legal(
    &self,
    loc: Loc,
    pla: Player,
    multi_stone_suicide_legal: bool,
  ) -> bool {
    if loc == PASS_LOC {
      return true;
    }
    if !self.on_board(loc) {
      return false;
    }
    if self.colors[loc as usize] != Color::Empty {
      return false;
    }
    if self.ko_loc == loc {
      return false;
    }
    if self.is_suicide(loc, pla) && !multi_stone_suicide_legal {
      return false;
    }
    true
  }

  pub fn is_legal_no_suicide(&self, loc: Loc, pla: Player) -> bool {
    self.is_legal(loc, pla, false)
  }

  /// Is `loc` a simple eye for `pla`?  (All four orthogonal neighbours are
  /// `pla`'s stones or the board edge, plus at most 1 diagonally missing stone
  /// of the right colour for corners/edges.)
  pub fn is_simple_eye(&self, loc: Loc, pla: Player) -> bool {
    let pla_color = pla.color();
    let all_adj_pla = self.adj.iter().all(|&off| {
      let c = self.colors[(loc as i16 + off) as usize];
      c == pla_color || c == Color::Wall
    });
    if !all_adj_pla {
      return false;
    }
    // Diagonals: at most one non-pla cell allowed (board edge or friendly stone).
    let diag_offsets = location::all_offsets(self.x_size);
    let bad_diags = diag_offsets[4..]
      .iter()
      .filter(|&&off| {
        let c = self.colors[(loc as i16 + off) as usize];
        c != pla_color && c != Color::Wall
      })
      .count();
    bad_diags <= 1
  }

  // -----------------------------------------------------------------------
  // Hash after hypothetical move
  // -----------------------------------------------------------------------

  /// Compute the position hash that would result from playing `loc` for `pla`,
  /// without actually modifying the board.  Used for superko checking.
  pub fn get_pos_hash_after_move(&self, loc: Loc, pla: Player) -> Hash128 {
    if loc == PASS_LOC {
      return self.pos_hash;
    }
    let z = zobrist();
    let opp_color = pla.opponent().color();
    let mut h = self.pos_hash;

    // Place the stone.
    h ^= z.board_hash[loc as usize][Color::Empty as usize];
    h ^= z.board_hash[loc as usize][pla.color() as usize];

    // Remove captured stones.
    for &off in &self.adj {
      let adj = (loc as i16 + off) as usize;
      if self.colors[adj] == opp_color
        && self.chain_data[self.chain_head[adj] as usize].num_liberties == 1
      {
        let head = self.chain_head[adj];
        let mut cur = head;
        loop {
          h ^= z.board_hash[cur as usize][opp_color as usize];
          h ^= z.board_hash[cur as usize][Color::Empty as usize];
          cur = self.next_in_chain[cur as usize];
          if cur == head {
            break;
          }
        }
      }
    }
    h
  }

  // -----------------------------------------------------------------------
  // Placing a stone (internal helpers)
  // -----------------------------------------------------------------------

  /// Initialise a new single-stone chain at `loc` for `pla`.
  fn add_chain(&mut self, loc: Loc, pla: Player) {
    let h = loc as usize;
    let libs = self.get_num_immediate_liberties(loc);
    self.chain_data[h] = ChainData {
      owner: pla as u8,
      num_locs: 1,
      num_liberties: libs,
    };
    self.chain_head[h] = loc;
    self.next_in_chain[h] = loc; // circular: points to itself
  }

  /// Merge chain containing `loc2` into chain containing `loc1` (the larger one
  /// becomes the head).  Returns the new head.
  fn merge_chains(&mut self, loc1: Loc, loc2: Loc) -> Loc {
    let mut h1 = self.chain_head[loc1 as usize];
    let mut h2 = self.chain_head[loc2 as usize];
    debug_assert_ne!(h1, h2);

    // Keep the larger chain as h1.
    if self.chain_data[h1 as usize].num_locs
      < self.chain_data[h2 as usize].num_locs
    {
      std::mem::swap(&mut h1, &mut h2);
    }

    self.chain_data[h1 as usize].num_locs +=
      self.chain_data[h2 as usize].num_locs;

    // Count new liberties contributed by h2's group.
    let mut new_libs = 0u16;
    let mut cur = h2;
    loop {
      for &off in &self.adj {
        let adj = (cur as i16 + off) as usize;
        if self.colors[adj] == Color::Empty
          && !self.is_liberty_of(adj as Loc, h1)
        {
          new_libs += 1;
        }
      }
      self.chain_head[cur as usize] = h1;
      if self.next_in_chain[cur as usize] == h2 {
        break;
      }
      cur = self.next_in_chain[cur as usize];
    }
    self.chain_data[h1 as usize].num_liberties += new_libs;

    // Link the two circular lists: h1 ↔ h2 ↔ … ↔ last2 ↔ next_of_h1 ↔ … ↔ h1
    let next1 = self.next_in_chain[h1 as usize];
    self.next_in_chain[h1 as usize] = h2;
    self.next_in_chain[cur as usize] = next1;

    h1
  }

  /// Is `empty_loc` a liberty of the chain whose head is `head`?
  fn is_liberty_of(&self, empty_loc: Loc, head: Loc) -> bool {
    let mut cur = head;
    loop {
      for &off in &self.adj {
        if (cur as i16 + off) as Loc == empty_loc {
          return true;
        }
      }
      cur = self.next_in_chain[cur as usize];
      if cur == head {
        break;
      }
    }
    false
  }

  /// Adjust the liberty count of every distinct `pla`-chain adjacent to `loc`
  /// by `delta`.  Avoids double-counting chains that touch `loc` multiple times.
  fn change_surrounding_liberties(
    &mut self,
    loc: Loc,
    pla: Player,
    delta: i16,
  ) {
    let pla_color = pla.color();
    let a = self.adj;
    let adjs = [
      (loc as i16 + a[0]) as usize,
      (loc as i16 + a[1]) as usize,
      (loc as i16 + a[2]) as usize,
      (loc as i16 + a[3]) as usize,
    ];
    // For each adjacent pla-stone, update its chain head's liberty count once.
    let mut seen = [NULL_LOC; 4];
    let mut n = 0;
    for &adj in &adjs {
      if self.colors[adj] == pla_color {
        let h = self.chain_head[adj];
        if !seen[..n].contains(&h) {
          seen[n] = h;
          n += 1;
          let libs = &mut self.chain_data[h as usize].num_liberties;
          *libs = (*libs as i16 + delta) as u16;
        }
      }
    }
  }

  /// Remove all stones of the chain headed at `head`, updating hashes and
  /// capture counts.
  fn remove_chain(&mut self, head: Loc) {
    let z = zobrist();
    let color = Color::from_u8(self.chain_data[head as usize].owner);
    let captured = self.chain_data[head as usize].num_locs as i32;
    let mut cur = head;
    loop {
      // Restore pos_hash.
      self.pos_hash ^= z.board_hash[cur as usize][color as usize];
      self.pos_hash ^= z.board_hash[cur as usize][Color::Empty as usize];

      // Free adjacent chains' liberties.
      let opp = match color {
        Color::Black => Player::White,
        _ => Player::Black,
      };
      self.change_surrounding_liberties(cur, opp, 1);

      self.colors[cur as usize] = Color::Empty;

      let next = self.next_in_chain[cur as usize];
      if next == head {
        break;
      }
      cur = next;
    }

    match color {
      Color::Black => self.num_white_captures += captured,
      Color::White => self.num_black_captures += captured,
      _ => {}
    }
  }

  // -----------------------------------------------------------------------
  // Play a move
  // -----------------------------------------------------------------------

  /// Play `loc` for `pla`, assuming it is legal.  Returns a `MoveRecord`
  /// that can be passed to `undo()`.
  pub fn play_move_assume_legal(
    &mut self,
    loc: Loc,
    pla: Player,
  ) -> MoveRecord {
    if loc == PASS_LOC {
      let rec = MoveRecord {
        loc,
        player: pla,
        ko_loc: self.ko_loc,
        captures: Vec::new(),
        pos_hash_before: self.pos_hash,
        num_black_captures_before: self.num_black_captures,
        num_white_captures_before: self.num_white_captures,
      };
      // Clear simple ko on pass.
      if self.ko_loc != NULL_LOC {
        let z = zobrist();
        self.pos_hash ^= z.ko_loc_hash[self.ko_loc as usize];
        self.ko_loc = NULL_LOC;
      }
      return rec;
    }

    let z = zobrist();
    let opp = pla.opponent();
    let opp_color = opp.color();
    let pla_color = pla.color();

    let prev_ko = self.ko_loc;
    let pos_hash_before = self.pos_hash;
    let nbc_before = self.num_black_captures;
    let nwc_before = self.num_white_captures;

    // Clear old ko from hash.
    if self.ko_loc != NULL_LOC {
      self.pos_hash ^= z.ko_loc_hash[self.ko_loc as usize];
      self.ko_loc = NULL_LOC;
    }

    // Place stone in hash.
    self.pos_hash ^= z.board_hash[loc as usize][Color::Empty as usize];
    self.pos_hash ^= z.board_hash[loc as usize][pla_color as usize];
    self.colors[loc as usize] = pla_color;

    // Remove adjacent liberties from friendly chains; they no longer see this cell.
    self.change_surrounding_liberties(loc, pla, -1);
    // Remove liberty from opponent chains adjacent to `loc`.
    self.change_surrounding_liberties(loc, opp, -1);

    // Copy adj offsets to avoid conflicting borrows in the loops below.
    let adj = self.adj;

    // Record captures for undo.
    let mut captures: Vec<CaptureRecord> = Vec::new();

    // Capture opponent chains that are now at 0 liberties.
    for &off in &adj {
      let a = (loc as i16 + off) as usize;
      if self.colors[a] == opp_color
        && self.chain_data[self.chain_head[a] as usize].num_liberties == 0
      {
        let head = self.chain_head[a];
        // Collect locs for undo record before removing.
        let mut locs = Vec::new();
        let mut cur = head;
        loop {
          locs.push(cur);
          cur = self.next_in_chain[cur as usize];
          if cur == head {
            break;
          }
        }
        captures.push(CaptureRecord {
          head,
          color: opp_color,
          locs,
        });
        self.remove_chain(head);
      }
    }

    // Build new stone's chain.
    self.add_chain(loc, pla);

    // Merge with adjacent friendly chains.
    for &off in &adj {
      let a = (loc as i16 + off) as usize;
      if self.colors[a] == pla_color {
        let h_adj = self.chain_head[a];
        let h_loc = self.chain_head[loc as usize];
        if h_adj != h_loc {
          self.merge_chains(loc, a as Loc);
        }
      }
    }

    // Simple ko detection: if exactly one stone was captured and the new stone
    // has exactly 1 liberty, set ko_loc to the captured stone's location.
    let new_ko = if captures.len() == 1
      && captures[0].locs.len() == 1
      && self.get_num_liberties(loc) == 1
    {
      let ko = captures[0].locs[0];
      self.ko_loc = ko;
      self.pos_hash ^= z.ko_loc_hash[ko as usize];
      ko
    } else {
      NULL_LOC
    };
    let _ = new_ko;

    MoveRecord {
      loc,
      player: pla,
      ko_loc: prev_ko,
      captures,
      pos_hash_before,
      num_black_captures_before: nbc_before,
      num_white_captures_before: nwc_before,
    }
  }

  /// Play `loc` for `pla`.  Returns `Ok(record)` if legal, `Err(())` otherwise.
  pub fn play_move(
    &mut self,
    loc: Loc,
    pla: Player,
    multi_stone_suicide_legal: bool,
  ) -> Result<MoveRecord, ()> {
    if !self.is_legal(loc, pla, multi_stone_suicide_legal) {
      return Err(());
    }
    Ok(self.play_move_assume_legal(loc, pla))
  }

  /// Undo the move described by `rec`, restoring the board to its prior state.
  pub fn undo(&mut self, rec: &MoveRecord) {
    let _pla = rec.player;

    // Restore captures first.
    for cap in rec.captures.iter().rev() {
      for &cap_loc in &cap.locs {
        self.colors[cap_loc as usize] = cap.color;
        // Rebuild chain_head/next_in_chain for restored group.
        self.chain_head[cap_loc as usize] = cap.head;
      }
      // Rebuild next_in_chain circular list.
      let n = cap.locs.len();
      for i in 0..n {
        self.next_in_chain[cap.locs[i] as usize] = cap.locs[(i + 1) % n];
      }
      self.chain_data[cap.head as usize] = ChainData {
        owner: cap.color as u8,
        num_locs: n as u16,
        num_liberties: 0, // will be recomputed below
      };
    }

    // Remove the played stone.
    if rec.loc != PASS_LOC {
      self.colors[rec.loc as usize] = Color::Empty;
    }

    // Restore position hash and capture counts.
    self.pos_hash = rec.pos_hash_before;
    self.num_black_captures = rec.num_black_captures_before;
    self.num_white_captures = rec.num_white_captures_before;

    // Restore ko.
    self.ko_loc = rec.ko_loc;

    // Full rebuild of chain_head, next_in_chain, chain_data (liberty counts).
    // This is simpler and correct; performance is not critical for undo.
    if rec.loc != PASS_LOC {
      self.rebuild_chains();
    }
  }

  /// Rebuild all chain metadata from scratch by scanning the board.
  /// O(board_area) — used only by undo.
  fn rebuild_chains(&mut self) {
    // Reset all chain metadata.
    for i in 0..MAX_ARR_SIZE {
      self.chain_head[i] = i as Loc;
      self.next_in_chain[i] = i as Loc;
      self.chain_data[i] = ChainData::default();
    }

    let mut visited = [false; MAX_ARR_SIZE];
    for y in 0..self.y_size {
      for x in 0..self.x_size {
        let loc = location::get_loc(x, y, self.x_size);
        let idx = loc as usize;
        let c = self.colors[idx];
        if !c.is_stone() || visited[idx] {
          continue;
        }
        // BFS to identify the connected component.
        let pla = c.player().unwrap();
        let mut group: Vec<Loc> = Vec::new();
        let mut queue = vec![loc];
        visited[idx] = true;
        while let Some(cur) = queue.pop() {
          group.push(cur);
          for &off in &self.adj {
            let adj = (cur as i16 + off) as usize;
            if self.colors[adj] == c && !visited[adj] {
              visited[adj] = true;
              queue.push(adj as Loc);
            }
          }
        }
        // Set up circular linked list: 0→1→2→…→n-1→0
        let n = group.len();
        let head = group[0];
        for i in 0..n {
          self.chain_head[group[i] as usize] = head;
          self.next_in_chain[group[i] as usize] = group[(i + 1) % n];
        }
        // Count liberties (unique empty cells adjacent to the group).
        let mut lib_set = std::collections::HashSet::new();
        for &stone in &group {
          for &off in &self.adj {
            let adj = (stone as i16 + off) as usize;
            if self.colors[adj] == Color::Empty {
              lib_set.insert(adj);
            }
          }
        }
        self.chain_data[head as usize] = ChainData {
          owner: pla as u8,
          num_locs: n as u16,
          num_liberties: lib_set.len() as u16,
        };
      }
    }
  }

  // -----------------------------------------------------------------------
  // Liberty count after a hypothetical move (capped)
  // -----------------------------------------------------------------------

  /// Returns the number of liberties the stone at `loc` would have after
  /// playing `pla` there, capped at `cap`.  Used for ladder and ko detection.
  pub fn get_num_liberties_after_play(
    &self,
    loc: Loc,
    pla: Player,
    cap: u16,
  ) -> u16 {
    if !self.on_board(loc) || self.colors[loc as usize] != Color::Empty {
      return 0;
    }
    let pla_color = pla.color();
    let opp_color = pla.opponent().color();
    let mut lib_set = std::collections::HashSet::new();

    // Immediate liberties of the new stone (excluding the cell being played).
    for &off in &self.adj {
      let adj = (loc as i16 + off) as usize;
      match self.colors[adj] {
        Color::Empty => {
          lib_set.insert(adj);
        }
        c if c == pla_color => {
          // Add liberties of friendly chain, excluding `loc` itself.
          let head = self.chain_head[adj];
          let mut cur = head;
          loop {
            for &off2 in &self.adj {
              let adj2 = (cur as i16 + off2) as usize;
              if adj2 != loc as usize && self.colors[adj2] == Color::Empty {
                lib_set.insert(adj2);
              }
            }
            cur = self.next_in_chain[cur as usize];
            if cur == head {
              break;
            }
          }
        }
        c if c == opp_color => {
          // If we capture this chain, its cells become empty liberties.
          if self.chain_data[self.chain_head[adj] as usize].num_liberties == 1 {
            let head = self.chain_head[adj];
            let mut cur = head;
            loop {
              if cur != loc {
                lib_set.insert(cur as usize);
              }
              cur = self.next_in_chain[cur as usize];
              if cur == head {
                break;
              }
            }
          }
        }
        _ => {}
      }
      if lib_set.len() as u16 >= cap {
        return cap;
      }
    }
    lib_set.len() as u16
  }

  // -----------------------------------------------------------------------
  // Board area / scoring (Benson's algorithm)
  // -----------------------------------------------------------------------

  /// Compute area ownership.  Returns a `[Color; MAX_ARR_SIZE]` where each
  /// board cell is assigned `Color::Black`, `Color::White`, or `Color::Empty`.
  ///
  /// Implements KataGo's pass-alive / Benson territory calculation.
  ///
  /// `safe_big_territories`: count large enclosed regions as owned.
  /// `unsafe_big_territories`: count regions that could still be invaded.
  /// `non_pass_alive_stones_go_to_empty`: treat all non-pass-alive stones as
  ///   empty for the purpose of area scoring.
  pub fn calculate_area(
    &self,
    safe_big_territories: bool,
    unsafe_big_territories: bool,
    non_pass_alive_stones_go_to_empty: bool,
    pla_alive_area: &mut [Color; MAX_ARR_SIZE],
  ) {
    let x_size = self.x_size;
    let y_size = self.y_size;

    // ----- Step 1: basic flood-fill to find empty regions -----
    // Each empty region is labelled; we track which player's stones border it.
    let mut region_id = [i16::MAX; MAX_ARR_SIZE];
    let mut regions: Vec<RegionInfo> = Vec::new();

    for y in 0..y_size {
      for x in 0..x_size {
        let loc = location::get_loc(x, y, x_size);
        if self.colors[loc as usize] != Color::Empty
          || region_id[loc as usize] != i16::MAX
        {
          continue;
        }
        let rid = regions.len() as i16;
        let mut borders_black = false;
        let mut borders_white = false;
        let mut q = vec![loc];
        region_id[loc as usize] = rid;
        let mut i = 0;
        while i < q.len() {
          let cur = q[i];
          i += 1;
          for &off in &self.adj {
            let adj = (cur as i16 + off) as usize;
            match self.colors[adj] {
              Color::Empty if region_id[adj] == i16::MAX => {
                region_id[adj] = rid;
                q.push(adj as Loc);
              }
              Color::Black => borders_black = true,
              Color::White => borders_white = true,
              _ => {}
            }
          }
        }
        regions.push(RegionInfo {
          borders_black,
          borders_white,
        });
      }
    }

    // ----- Step 2: classify stones as pass-alive via Benson -----
    // (Simplified: iterate until no more groups are removed.)
    let mut alive = [false; MAX_ARR_SIZE];

    // Initial: all stones potentially alive.
    for y in 0..y_size {
      for x in 0..x_size {
        let loc = location::get_loc(x, y, x_size) as usize;
        if self.colors[loc].is_stone() {
          alive[loc] = true;
        }
      }
    }

    // For Benson: iterate removing groups with < 2 safe liberties.
    loop {
      let mut changed = false;
      let mut visited = [false; MAX_ARR_SIZE];
      for y in 0..y_size {
        for x in 0..x_size {
          let loc = location::get_loc(x, y, x_size) as usize;
          if !self.colors[loc].is_stone() || visited[loc] || !alive[loc] {
            continue;
          }
          let pla = self.colors[loc].player().unwrap();
          let head = self.chain_head[loc] as usize;

          // BFS over the chain.
          let mut chain_locs = Vec::new();
          let mut cur = head as Loc;
          loop {
            visited[cur as usize] = true;
            chain_locs.push(cur);
            cur = self.next_in_chain[cur as usize];
            if cur as usize == head {
              break;
            }
          }

          // Count vital regions (surrounded by at least 2 pla stones, no opp stones).
          let adj_copy = self.adj;
          let mut vital_regions = std::collections::HashSet::<i16>::new();
          for &s in &chain_locs {
            for &off in &adj_copy {
              let a = (s as i16 + off) as usize;
              if self.colors[a] == Color::Empty {
                let rid = region_id[a];
                if rid == i16::MAX {
                  continue;
                }
                let ri = &regions[rid as usize];
                let vital = match pla {
                  Player::Black => !ri.borders_white,
                  Player::White => !ri.borders_black,
                };
                if vital {
                  vital_regions.insert(rid);
                }
              }
            }
          }

          if vital_regions.len() < 2 {
            // Kill this chain.
            for &s in &chain_locs {
              alive[s as usize] = false;
            }
            changed = true;
          }
        }
      }
      if !changed {
        break;
      }
    }

    // ----- Step 3: assign ownership -----
    for i in 0..MAX_ARR_SIZE {
      pla_alive_area[i] = Color::Empty;
    }

    for y in 0..y_size {
      for x in 0..x_size {
        let loc = location::get_loc(x, y, x_size) as usize;
        match self.colors[loc] {
          Color::Black if alive[loc] => pla_alive_area[loc] = Color::Black,
          Color::White if alive[loc] => pla_alive_area[loc] = Color::White,
          Color::Black | Color::White if non_pass_alive_stones_go_to_empty => {
            pla_alive_area[loc] = Color::Empty;
          }
          Color::Empty => {
            let rid = region_id[loc];
            if rid == i16::MAX {
              continue;
            }
            let ri = &regions[rid as usize];
            if !safe_big_territories && !unsafe_big_territories {
              // Only definitely enclosed territory.
              if ri.borders_black && !ri.borders_white {
                pla_alive_area[loc] = Color::Black;
              } else if ri.borders_white && !ri.borders_black {
                pla_alive_area[loc] = Color::White;
              }
            } else {
              if ri.borders_black && !ri.borders_white {
                pla_alive_area[loc] = Color::Black;
              } else if ri.borders_white && !ri.borders_black {
                pla_alive_area[loc] = Color::White;
              }
            }
          }
          _ => {}
        }
      }
    }
  }

  // -----------------------------------------------------------------------
  // Ladder detection
  // -----------------------------------------------------------------------

  /// Is the string containing `loc` (which must be a stone of `pla`) captured
  /// by a ladder even with best play by the defender?
  ///
  /// Returns `true` if the group is ladder-captured.
  /// Budget-limited: stops after `MAX_NODES` internal states examined and
  /// returns `false` (assume not captured, safer default).
  pub fn search_is_ladder_captured(&self, loc: Loc, pla: Player) -> bool {
    if !self.on_board(loc) || self.colors[loc as usize] != pla.color() {
      return false;
    }
    let libs = self.get_num_liberties(loc);
    if libs >= 3 {
      return false;
    }
    if libs <= 0 {
      return true;
    }

    const MAX_NODES: usize = 25_000;
    let mut board = self.clone();
    let mut node_count = 0usize;
    Self::ladder_search_inner(
      &mut board,
      loc,
      pla,
      libs,
      &mut node_count,
      MAX_NODES,
    )
  }

  fn ladder_search_inner(
    board: &mut Board,
    loc: Loc,
    pla: Player,
    libs: u16,
    node_count: &mut usize,
    max_nodes: usize,
  ) -> bool {
    *node_count += 1;
    if *node_count >= max_nodes {
      return false;
    }

    let opp = pla.opponent();

    if libs <= 0 {
      return true;
    }
    if libs >= 3 {
      return false;
    }

    if libs == 1 {
      // Defender: try to escape to the single liberty.
      let liberty = board.find_liberty(loc, pla);
      let Some(escape) = liberty else {
        return true;
      };
      if !board.is_legal(escape, pla, true) {
        return true;
      }
      let rec_def = board.play_move_assume_legal(escape, pla);
      let after_def_libs = board.get_num_liberties(escape);
      if after_def_libs == 0 {
        board.undo(&rec_def);
        return true;
      }
      if after_def_libs >= 3 {
        board.undo(&rec_def);
        return false; // defender escaped cleanly
      }
      // Defender has 1 or 2 libs after escaping — attacker now picks the best attacking move.
      // Find liberties of the escaped chain and try each as an attacker move.
      let mut atk1 = NULL_LOC;
      let mut atk2 = NULL_LOC;
      board.find_two_liberties(escape, pla, &mut atk1, &mut atk2);
      let mut attacker_wins = false;
      for &atk in &[atk1, atk2] {
        if atk == NULL_LOC {
          continue;
        }
        if !board.is_legal(atk, opp, true) {
          continue;
        }
        let rec_atk = board.play_move_assume_legal(atk, opp);
        let remaining_libs = board.get_num_liberties(escape);
        let captured = if remaining_libs == 0 {
          true
        } else {
          Self::ladder_search_inner(
            board,
            escape,
            pla,
            remaining_libs,
            node_count,
            max_nodes,
          )
        };
        board.undo(&rec_atk);
        if captured {
          attacker_wins = true;
          break;
        }
      }
      board.undo(&rec_def);
      return attacker_wins;
    }

    // libs == 2: attacker tries all adjacent moves to reduce liberties.
    let mut lib1 = NULL_LOC;
    let mut lib2 = NULL_LOC;
    board.find_two_liberties(loc, pla, &mut lib1, &mut lib2);

    // Try both attacking moves.
    for &atk in &[lib1, lib2] {
      if atk == NULL_LOC {
        continue;
      }
      if !board.is_legal(atk, opp, true) {
        continue;
      }
      let rec = board.play_move_assume_legal(atk, opp);
      let new_libs = board.get_num_liberties(loc);
      let captured = if new_libs == 0 {
        true
      } else {
        Self::ladder_search_inner(
          board, loc, pla, new_libs, node_count, max_nodes,
        )
      };
      board.undo(&rec);
      if captured {
        return true;
      } // attacker found a working move
    }
    false // defender can escape via one of the liberties
  }

  fn find_liberty(&self, loc: Loc, pla: Player) -> Option<Loc> {
    let pla_color = pla.color();
    let head = self.chain_head[loc as usize];
    let mut cur = head;
    loop {
      for &off in &self.adj {
        let adj = (cur as i16 + off) as usize;
        if self.colors[adj] == Color::Empty {
          return Some(adj as Loc);
        }
      }
      cur = self.next_in_chain[cur as usize];
      if cur == head {
        break;
      }
    }
    let _ = pla_color;
    None
  }

  fn find_two_liberties(
    &self,
    loc: Loc,
    pla: Player,
    lib1: &mut Loc,
    lib2: &mut Loc,
  ) {
    let _pla_color = pla.color();
    let head = self.chain_head[loc as usize];
    let mut cur = head;
    *lib1 = NULL_LOC;
    *lib2 = NULL_LOC;
    loop {
      for &off in &self.adj {
        let adj = (cur as i16 + off) as usize;
        if self.colors[adj] == Color::Empty {
          if *lib1 == NULL_LOC {
            *lib1 = adj as Loc;
          } else if adj as Loc != *lib1 && *lib2 == NULL_LOC {
            *lib2 = adj as Loc;
            return;
          }
        }
      }
      cur = self.next_in_chain[cur as usize];
      if cur == head {
        break;
      }
    }
  }

  // -----------------------------------------------------------------------
  // Simple display
  // -----------------------------------------------------------------------

  pub fn to_string_simple(&self) -> String {
    let mut s = String::new();
    for y in 0..self.y_size {
      for x in 0..self.x_size {
        let loc = location::get_loc(x, y, self.x_size);
        let c = match self.colors[loc as usize] {
          Color::Black => 'X',
          Color::White => 'O',
          _ => '.',
        };
        s.push(c);
      }
      s.push('\n');
    }
    s
  }
}

// ---------------------------------------------------------------------------
// Region info (used in calculate_area)
// ---------------------------------------------------------------------------

struct RegionInfo {
  borders_black: bool,
  borders_white: bool,
}

// ---------------------------------------------------------------------------
// Color helper
// ---------------------------------------------------------------------------

impl Color {
  fn from_u8(v: u8) -> Self {
    match v {
      0 => Color::Empty,
      1 => Color::Black,
      2 => Color::White,
      _ => Color::Wall,
    }
  }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
  use super::*;

  fn black_at(b: &mut Board, x: usize, y: usize) {
    b.play_move_assume_legal(location::get_loc(x, y, b.x_size), Player::Black);
  }
  fn white_at(b: &mut Board, x: usize, y: usize) {
    b.play_move_assume_legal(location::get_loc(x, y, b.x_size), Player::White);
  }

  #[test]
  fn empty_board_has_correct_size() {
    let b = Board::new(9, 9);
    assert_eq!(b.x_size, 9);
    assert_eq!(b.y_size, 9);
    for y in 0..9 {
      for x in 0..9 {
        let loc = location::get_loc(x, y, 9);
        assert_eq!(b.colors[loc as usize], Color::Empty);
      }
    }
  }

  #[test]
  fn place_stone_changes_color() {
    let mut b = Board::new(9, 9);
    let loc = location::get_loc(3, 3, 9);
    b.play_move_assume_legal(loc, Player::Black);
    assert_eq!(b.colors[loc as usize], Color::Black);
  }

  #[test]
  fn single_stone_has_four_liberties() {
    let mut b = Board::new(9, 9);
    let loc = location::get_loc(4, 4, 9);
    b.play_move_assume_legal(loc, Player::Black);
    assert_eq!(b.get_num_liberties(loc), 4);
  }

  #[test]
  fn corner_stone_has_two_liberties() {
    let mut b = Board::new(9, 9);
    let loc = location::get_loc(0, 0, 9);
    b.play_move_assume_legal(loc, Player::Black);
    assert_eq!(b.get_num_liberties(loc), 2);
  }

  #[test]
  fn capture_single_stone() {
    let mut b = Board::new(9, 9);
    // Surround (1,1) with white stones on 4 sides.
    let target = location::get_loc(1, 1, 9);
    b.play_move_assume_legal(target, Player::Black);
    white_at(&mut b, 0, 1);
    white_at(&mut b, 2, 1);
    white_at(&mut b, 1, 0);
    white_at(&mut b, 1, 2);
    assert_eq!(
      b.colors[target as usize],
      Color::Empty,
      "stone should be captured"
    );
    assert_eq!(b.num_black_captures, 0);
    assert_eq!(b.num_white_captures, 1);
  }

  #[test]
  fn ko_is_set_after_ko_capture() {
    // Ko setup on 5x5:
    // W at (1,1) has 1 liberty: (1,2).
    // B surrounds W at (0,1),(2,1),(1,0).
    // W at (0,2),(2,2),(1,3) surround the capture spot (1,2) on 3 sides.
    // B plays (1,2): captures W at (1,1). B at (1,2) has 1 liberty=(1,1) → ko!
    let mut b = Board::new(5, 5);
    // Place W and surrounding B first (W can be placed normally since it has a liberty at (1,2)).
    white_at(&mut b, 1, 1);
    black_at(&mut b, 0, 1);
    black_at(&mut b, 2, 1);
    black_at(&mut b, 1, 0);
    // Place W stones around (1,2) so B there will have 1 liberty.
    white_at(&mut b, 0, 2);
    white_at(&mut b, 2, 2);
    white_at(&mut b, 1, 3);
    // B plays (1,2): captures W at (1,1).
    let cap = location::get_loc(1, 2, 5);
    b.play_move_assume_legal(cap, Player::Black);
    assert_eq!(
      b.colors[location::get_loc(1, 1, 5) as usize],
      Color::Empty,
      "W should be captured"
    );
    assert_ne!(b.ko_loc, NULL_LOC, "ko should be set");
    assert_eq!(
      b.ko_loc,
      location::get_loc(1, 1, 5),
      "ko at captured location"
    );
  }

  #[test]
  fn ko_prevents_retake() {
    let mut b = Board::new(5, 5);
    white_at(&mut b, 1, 1);
    black_at(&mut b, 0, 1);
    black_at(&mut b, 2, 1);
    black_at(&mut b, 1, 0);
    white_at(&mut b, 0, 2);
    white_at(&mut b, 2, 2);
    white_at(&mut b, 1, 3);
    let cap = location::get_loc(1, 2, 5);
    b.play_move_assume_legal(cap, Player::Black);
    assert_ne!(b.ko_loc, NULL_LOC, "ko should be set");
    let ko = b.ko_loc;
    assert!(
      !b.is_legal(ko, Player::White, false),
      "ko retake should be illegal"
    );
  }

  #[test]
  fn undo_restores_board() {
    let mut b = Board::new(9, 9);
    let loc = location::get_loc(4, 4, 9);
    let hash_before = b.pos_hash;
    let rec = b.play_move_assume_legal(loc, Player::Black);
    b.undo(&rec);
    assert_eq!(b.colors[loc as usize], Color::Empty);
    assert_eq!(b.pos_hash, hash_before);
  }

  #[test]
  fn undo_after_capture() {
    let mut b = Board::new(5, 5);
    let target = location::get_loc(2, 2, 5);
    black_at(&mut b, 2, 2);
    white_at(&mut b, 1, 2);
    white_at(&mut b, 3, 2);
    white_at(&mut b, 2, 1);
    let hash_before = b.pos_hash;
    let captures_before = b.num_black_captures;
    let rec =
      b.play_move_assume_legal(location::get_loc(2, 3, 5), Player::White);
    assert_eq!(
      b.colors[target as usize],
      Color::Empty,
      "should be captured"
    );
    b.undo(&rec);
    assert_eq!(
      b.colors[target as usize],
      Color::Black,
      "stone should be restored"
    );
    assert_eq!(b.pos_hash, hash_before);
    assert_eq!(b.num_black_captures, captures_before);
  }

  #[test]
  fn chain_merge_and_liberties() {
    let mut b = Board::new(9, 9);
    black_at(&mut b, 3, 3);
    black_at(&mut b, 4, 3);
    // Two adjacent stones should form one chain.
    let loc1 = location::get_loc(3, 3, 9);
    let loc2 = location::get_loc(4, 3, 9);
    assert_eq!(
      b.chain_head[loc1 as usize], b.chain_head[loc2 as usize],
      "should be same chain"
    );
    assert_eq!(
      b.get_num_liberties(loc1),
      6,
      "two stones in a row have 6 liberties"
    );
  }

  #[test]
  fn pass_clears_ko() {
    let mut b = Board::new(5, 5);
    white_at(&mut b, 1, 1);
    black_at(&mut b, 0, 1);
    black_at(&mut b, 2, 1);
    black_at(&mut b, 1, 0);
    // Surround (1,2) with W so the capturing B stone has exactly 1 liberty.
    white_at(&mut b, 0, 2);
    white_at(&mut b, 2, 2);
    white_at(&mut b, 1, 3);
    b.play_move_assume_legal(location::get_loc(1, 2, 5), Player::Black);
    assert_ne!(b.ko_loc, NULL_LOC, "ko should be set before pass");
    b.play_move_assume_legal(PASS_LOC, Player::White);
    assert_eq!(b.ko_loc, NULL_LOC, "ko should clear on pass");
  }

  #[test]
  fn pos_hash_changes_with_each_move() {
    let mut b = Board::new(9, 9);
    let h0 = b.pos_hash;
    b.play_move_assume_legal(location::get_loc(3, 3, 9), Player::Black);
    let h1 = b.pos_hash;
    b.play_move_assume_legal(location::get_loc(4, 4, 9), Player::White);
    let h2 = b.pos_hash;
    assert_ne!(h0, h1);
    assert_ne!(h1, h2);
  }

  #[test]
  fn is_simple_eye_recognises_eye() {
    let mut b = Board::new(5, 5);
    // For an interior eye at (2,2): all 4 orthogonal AND all 4 diagonal neighbors must be B.
    black_at(&mut b, 1, 2); // left
    black_at(&mut b, 3, 2); // right
    black_at(&mut b, 2, 1); // up
    black_at(&mut b, 2, 3); // down
    black_at(&mut b, 1, 1); // UL diagonal
    black_at(&mut b, 3, 1); // UR diagonal
    black_at(&mut b, 1, 3); // DL diagonal
    black_at(&mut b, 3, 3); // DR diagonal
    let eye = location::get_loc(2, 2, 5);
    assert!(b.is_simple_eye(eye, Player::Black), "should be simple eye");
    assert!(
      !b.is_simple_eye(eye, Player::White),
      "should not be white eye"
    );
  }

  #[test]
  fn calculate_area_single_prisoner() {
    let mut b = Board::new(5, 5);
    // Surround a 1x1 black territory with white.
    // B enclosed region = (0,0), white stones on (1,0),(0,1).
    white_at(&mut b, 1, 0);
    white_at(&mut b, 2, 0);
    white_at(&mut b, 2, 1);
    white_at(&mut b, 2, 2);
    white_at(&mut b, 1, 2);
    white_at(&mut b, 0, 2);
    white_at(&mut b, 0, 1);
    let mut area = [Color::Empty; MAX_ARR_SIZE];
    b.calculate_area(true, false, false, &mut area);
    // (0,0) is enclosed by white — should be White territory.
    let enc = location::get_loc(0, 0, 5) as usize;
    assert_eq!(
      area[enc],
      Color::White,
      "enclosed corner should be white territory"
    );
  }

  #[test]
  fn ladder_detects_captured_stone() {
    // A stone with 0 liberties is trivially captured (base case in search_is_ladder_captured).
    // We test by checking get_num_liberties directly for the setup validity.

    // A stone with 4 liberties on an open board is not ladder-captured.
    let mut b = Board::new(9, 9);
    black_at(&mut b, 4, 4);
    let loc = location::get_loc(4, 4, 9);
    assert_eq!(b.get_num_liberties(loc), 4);
    assert!(
      !b.search_is_ladder_captured(loc, Player::Black),
      "stone with 4 liberties should not be ladder-captured"
    );

    // A stone with 2 liberties that is not a ladder (can escape freely) is not captured.
    let mut b2 = Board::new(9, 9);
    black_at(&mut b2, 4, 4);
    white_at(&mut b2, 3, 4);
    white_at(&mut b2, 4, 3);
    let loc2 = location::get_loc(4, 4, 9);
    assert_eq!(b2.get_num_liberties(loc2), 2);
    // B can escape into the open board — not ladder-captured.
    assert!(
      !b2.search_is_ladder_captured(loc2, Player::Black),
      "stone with 2 open liberties should not be ladder-captured"
    );
  }
}
